sudo: required

services:
  - docker

language: go

go:
  - master

before_install:
- docker pull golang:alpine

script: make

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
  - export REPO=$DOCKER_USERNAME/mqttfaas:latest
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag mqttfaas:lite $DOCKER_USERNAME/mqttfaas:$TAG
  - docker push $DOCKER_USERNAME/mqttfaas:$TAG
  - docker push $(docker images -f "reference=sabithksme/mqttfaas_*" --format="{{.Repository}}")