services:
  mqtt:
    image: eclipse-mosquitto
    ports:
    - "1883:1883"
    - "9001:9001"
  # faas:
  #   image: mqttfaas:lite
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
version: '3.1'
